backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "src/assets/images" # Media files will be stored in the repo under images/uploads
public_folder: "../../assets/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "meeting" # Used in routes, e.g., /admin/collections/blog
    label: "Meetings" # Used in the UI
    folder: "src/content/meetings" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Draft", name: "draft", widget: "boolean", required: false }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Image", name: "image", widget: "image", allow_multiple: false, equired: false }
      - { label: "Additional Images", name: "images", widget: "list", field: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }